services:
  manager:
    build:
      dockerfile: Manager/Dockerfile
    volumes:
      - ./appsettings.json:/app/appsettings.json:ro
    image: ghcr.io/kubaz2/sharp/manager:latest
    ports:
      - 8080:8080
    networks:
      - runner
      - asm
    depends_on:
      - runner
      - asm
    restart: unless-stopped
      
  runner:
    build:
      context: ..
      dockerfile: Backend/Sandbox/Runner/Dockerfile
    image: ghcr.io/kubaz2/sharp/runner:latest
    networks:
      - runner
    privileged: true
    restart: unless-stopped

  asm:
    build:
      context: ..
      dockerfile: Backend/Sandbox/Asm/Dockerfile
    image: ghcr.io/kubaz2/sharp/asm:latest
    networks:
      - asm
    privileged: true
    restart: unless-stopped

networks:
  runner:
    driver: bridge
  asm:
    driver: bridge
