services:
  manager:
    build:
      dockerfile: Manager/Dockerfile
    ports:
      - 8080:8080
    networks:
      - runner
      - asm
    depends_on:
      - runner
      - asm
    restart: unless-stopped
      
  runner:
    build:
      context: ..
      dockerfile: Backend/Sandbox/Runner/Dockerfile
    networks:
      - runner
    privileged: true
    restart: unless-stopped

  asm:
    build:
      context: ..
      dockerfile: Backend/Sandbox/Asm/Dockerfile
    networks:
      - asm
    privileged: true
    restart: unless-stopped

networks:
  runner:
    driver: bridge
  asm:
    driver: bridge
