services:
  manager:
    build:
      dockerfile: Manager/Dockerfile
    ports:
      - 8080:8080
    networks:
      - runner
      - asm
    depends_on:
      - runner
      - asm
    restart: always
      
  runner:
    build:
      dockerfile: Sandbox/Runner/Dockerfile
    networks:
      - runner
    privileged: true
    restart: always

  asm:
    build:
      dockerfile: Sandbox/Asm/Dockerfile
    networks:
      - asm
    privileged: true
    restart: always

networks:
  runner:
    driver: bridge
  asm:
    driver: bridge
